accessibility: protected
containerPort: 5000

wardenProxy: "enabled"

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  periodSeconds: 5

resources:
    requests:
        cpu: 20m
        memory: 64Mi
    limits:
        cpu: 20m
        memory: 64Mi
